logging:
  level:
    org:
      springframework:
        security: trace
spring:
  profiles:
    active: dev
server:
  port: 5454

jwt:
  secret:
    key: 'basdba123@@@dbasdsabbasadasdsadadasd_ssaasasadddwww'
    expirationMs: 3600000

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/fb
    password: nam0827770132
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem


---

#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: student_vzmt_user
#    url: jdbc:postgresql://dpg-cmmdabi1hbls73cf9qkg-a.singapore-postgres.render.com/student_vzmt
#    password: BzELocsCqi4J0FNQPa86Z6DTpK59Z50r
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: 'true'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect